name: Scheduled Upstream Sync

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight (UTC)
  workflow_dispatch: # Allows you to manually trigger it via the Actions tab

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Fork
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_branch: main
          upstream_sync_repo: freqtrade/freqtrade
